### PR TITLE
Updated simulator to newest grbl version and changed make to cmake

### PR DESCRIPTION
**Pull request by vgerber**
- Fixed some properties for newest grbl version
- Replaced old make toolchain with cmake for cleaner builds
- Improved readme
- src tree clean up

### CODE REVIEW

**Comment by terjeio** [comment]
Did I just make a problem for the merge by updating the changelog in the core (the grbl folder)?

BTW is it possible to import the [core CMakeLists.txt](https://github.com/grblHAL/core/blob/master/CMakeLists.txt) instead of duplicating it in this project?

**Comment by vgerber** [comment]
I will take a look. Never worked with submodules before

**Comment by vgerber** [comment]
Including the grbl core CMakeLists.txt only removes the .c files and adds a new library for linking. I still have to manually collect all header files in the cmake file. This might only increases the complexity.
If the file provides the header files for includes too, including the core cmake file might be a good choice

**Comment by vgerber** [comment]
I moved the grbl submodule dir into the new src dir. Looks like git does not love what is happening, but a rebase fixed that

**Pull request merged**
