### PR TITLE
Fix simulator to work with latest grbl

### PR DESCRIPTION
**Pull request by infnorm**
- Fixed CMakeLists to have missing files.
- Fixed build to work on apple (by not including rt)
- Fixed to new update interface in HAL (takes mask now)
- Register a spindle so driver check succeeds.
- Update driver version
- Remove pwm linearization option setting which seems not to exist.
- Update hal signature for limit switches in hal

### CODE REVIEW

**Comment by terjeio** [comment]
My main Linux server was too old to be upgraded to the required cmake version (after the PR swithing to cmake)  so I have not been able to compile. Thus this driver has not been maintained as it should.
The [Web Builder](svn.io-engineering.com:8080/) server is more up to date so I guess that can be used, maybe even for building via the Web Builder?

But then one could argue that the simulator is no longer needed since it is possible to get grblHAL up and running without installing any software at all. Pi Pico/Pi Pico W and STM Nucleo boards can be flashed by dropping the firmware (generated by the Web Builder) on a virtual drive provided by the bootloader or on-board debug probe. And a Pi Pico is less than EUR 10...

Anyway I need a bit more time, and preferably a working tool chain, to comment on the changes.  One immediate comment would be that I wonder if the spindle HAL pointers could be set by instantiating the NULL spindle by `calling spindle_add_null()` from the simulator drivers?

**Comment by terjeio** [comment]
I have now been able to build with the Web Builder server and the code was in a sad state. I tried to merge your changes but could not due to the grbl submodule is part of the PR - and I am too stupid to figure out how to get past that. Git is a complex piece of software that I have a hard time to understand the fine detalis of...

Anyway, I have both the simulator and validator running and at least compiling for Linux with the Web Builder is within reach. Cross compiling for Windows and Mac is perhaps possible but I have not researched that.

I can commit my changes if it is ok with you, or if you can fix the PR so it can be merged I can apply my changes afterwards.
What do you think?

**Comment by infnorm** [comment]
I did a rebase against your updates on master, so it now appears to allow merging cleanly.

I do have RP2040's, but I do like being able to develop anywhere. I also sort of hope that I could maybe use something like simulator to export a library for doing interpretation of gcode to make senders more accurate. There's many gcode interpreters but only LinuxCNC and grblHal support extensions like exprs... who doesn't want to write G1 as G[3-2] :).

**Comment by terjeio** [comment]
> ... to make senders more accurate.

I am curious about what you mean by that.

**Comment by infnorm** [comment]
To make previews more accurate. The limit of what a preview can show is how accurately it models what is happening in the controller. One idea would be to ask the controller (grblHAL) to run in simulation mode and output drawing commands. Another idea would be to have the PC run the same code as grblHAL. I.e. I'm updating bCNC and right now it interprets gcode itself to draw it, but it knows nothing of [], conditionals, loops, etc.

**Comment by terjeio** [comment]
Thanks for feedback. Not easy to get all the new stuff integrated in a sender, I have attempted a few bits of it in ioSender - e.g. reading parameter values from the controller with `$#`.
FYI the [Web Builder](http://svn.io-engineering.com:8080/?driver=Simulator) can now be used to build Linux and Windows executables, Windows version updated to uses native libraries only. I'll commit the changes later,
Cross-compiling for MacOs seems to be a challenge, not sure I will attempt that since I do not have a Mac machine.

**Pull request merged**
